### ISSUE TITLE
Broken link in Privacy Policy.

### ISSUE THREAD

**Issue by MarioRicalde** [ethi-technologies/policies#2]
#### 1. What's the name of the policy?

Privacy Policy

#### 2. Is this issue related to a specific section within one of our policies (e.g. the Terms of Service)? If so, please include a link to the section or subsection.

The link is broken for the "privacy contact form".

https://github.com/ethi-technologies/policies/blob/master/ethi-privacy-statement.md#resolving-complaints

#### 3. Did you already open a pull request? If so, please include a link to the PR.

No.

#### 5. Why do you think this section or language needs improvement?

N/a

**Comment by michaeljelly** [comment]
Hey Mario, thanks - have fixed now.
